"""
catalog.py — Strategy catalog: 155 named StrategySpec entries across 13 families.
Data-driven registry; the generic builder resolves templates to concrete legs.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Optional
from .legs import (
    RISK_DEFINED, RISK_LIMITED, RISK_UNDEFINED,
    MODE_AUTONOMOUS, MODE_ANALYSIS_ONLY,
    ASSET_CALL, ASSET_PUT, ASSET_STOCK, SIDE_LONG, SIDE_SHORT,
)

# ── Strategy families ────────────────────────────────────────────────────────
FAMILY_SINGLE      = "SINGLE_LEG"
FAMILY_STOCK_OPT   = "STOCK_PLUS_OPTION"
FAMILY_CALL_SPREAD = "CALL_SPREADS"
FAMILY_PUT_SPREAD  = "PUT_SPREADS"
FAMILY_SYNTHETIC   = "SYNTHETIC_COMBINATION"
FAMILY_CALENDAR    = "CALENDAR"
FAMILY_DIAGONAL    = "DIAGONAL"
FAMILY_STRADDLE    = "STRADDLE_STRANGLE"
FAMILY_BUTTERFLY   = "BUTTERFLY"
FAMILY_CONDOR      = "CONDOR"
FAMILY_RATIO       = "RATIO_BACKSPREAD"
FAMILY_ADVANCED    = "ADVANCED_INCOME_VOL"
FAMILY_EVENT       = "EVENT_EXPIRATION"

# ── Directions / vol theses ──────────────────────────────────────────────────
BULL, BEAR, NEUTRAL, ANY = "BULLISH", "BEARISH", "NEUTRAL", "ANY"
HIGH_IV, LOW_IV, VOL_ANY = "HIGH_IV", "LOW_IV", "NEUTRAL"


@dataclass(frozen=True)
class StrategySpec:
    name:           str
    family:         str
    aliases:        tuple = field(default_factory=tuple)
    risk_class:     str   = RISK_DEFINED
    execution_mode: str   = MODE_AUTONOMOUS
    direction:      str   = ANY
    vol_thesis:     str   = VOL_ANY
    min_legs:       int   = 1
    max_legs:       int   = 4
    has_stock:      bool  = False
    # leg_templates: list of dicts {asset_type, side, delta_target, dte_slot, offset, ratio}
    leg_templates:  tuple = field(default_factory=tuple)
    min_dte:        int   = 2
    max_dte:        int   = 730
    notes:          str   = ""

def _lt(asset_type, side, delta=0.50, slot="FRONT", offset=0, ratio=1):
    return {"asset_type": asset_type, "side": side, "delta_target": delta,
            "dte_slot": slot, "strike_offset": offset, "ratio": ratio}

def _call(side, delta=0.50, slot="FRONT", offset=0, ratio=1):
    return _lt(ASSET_CALL, side, delta, slot, offset, ratio)

def _put(side, delta=0.50, slot="FRONT", offset=0, ratio=1):
    return _lt(ASSET_PUT, side, delta, slot, offset, ratio)

def _stock(side, ratio=1):
    return _lt(ASSET_STOCK, side, 0, "FRONT", 0, ratio)

# ═══════════════════════════════════════════════════════════════════════════
# CATALOG — 155 strategy definitions
# ═══════════════════════════════════════════════════════════════════════════
CATALOG: List[StrategySpec] = [

    # ── 1. SINGLE_LEG (8) ────────────────────────────────────────────────
    StrategySpec("Long Call", FAMILY_SINGLE,
        aliases=("buy call",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=LOW_IV, min_legs=1, max_legs=1,
        leg_templates=(_call(SIDE_LONG, 0.40),),
        notes="Defined risk via premium paid; unlimited upside.",
    ),
    StrategySpec("Long Put", FAMILY_SINGLE,
        aliases=("buy put",), risk_class=RISK_DEFINED, direction=BEAR,
        vol_thesis=LOW_IV, min_legs=1, max_legs=1,
        leg_templates=(_put(SIDE_LONG, 0.40),),
    ),
    StrategySpec("Cash-Secured Put", FAMILY_SINGLE,
        aliases=("csp",), risk_class=RISK_LIMITED, direction=BULL,
        vol_thesis=HIGH_IV, min_legs=1, max_legs=1,
        leg_templates=(_put(SIDE_SHORT, 0.30),),
        notes="Max loss = strike - premium; requires cash collateral.",
    ),
    StrategySpec("Covered Short Call", FAMILY_SINGLE,
        aliases=("naked call analysis",), risk_class=RISK_UNDEFINED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=BEAR,
        min_legs=1, max_legs=1, leg_templates=(_call(SIDE_SHORT, 0.40),),
        notes="Analysis-only unless stock leg added (covered call).",
    ),
    StrategySpec("LEAPS Call", FAMILY_SINGLE,
        aliases=("leaps long call",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=LOW_IV, min_legs=1, max_legs=1, min_dte=181, max_dte=730,
        leg_templates=(_call(SIDE_LONG, 0.70, slot="LEAPS"),),
    ),
    StrategySpec("LEAPS Put", FAMILY_SINGLE,
        aliases=("leaps long put",), risk_class=RISK_DEFINED, direction=BEAR,
        vol_thesis=LOW_IV, min_legs=1, max_legs=1, min_dte=181, max_dte=730,
        leg_templates=(_put(SIDE_LONG, 0.70, slot="LEAPS"),),
    ),
    StrategySpec("Deep-ITM Call", FAMILY_SINGLE,
        aliases=("stock replacement call", "deep itm call"),
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=1, max_legs=1,
        leg_templates=(_call(SIDE_LONG, 0.80),),
        notes="Stock replacement; high delta; minimal time value.",
    ),
    StrategySpec("Deep-ITM Put", FAMILY_SINGLE,
        aliases=("stock replacement put", "deep itm put"),
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=1, max_legs=1,
        leg_templates=(_put(SIDE_LONG, 0.80),),
    ),

    # ── 2. STOCK_PLUS_OPTION (18) ─────────────────────────────────────────
    StrategySpec("Covered Call", FAMILY_STOCK_OPT,
        aliases=("buy write covered call",), risk_class=RISK_LIMITED,
        direction=BULL, vol_thesis=HIGH_IV, min_legs=2, max_legs=2,
        has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _call(SIDE_SHORT, 0.30)),
        notes="Long 100 shares + short OTM call. Max profit capped at strike.",
    ),
    StrategySpec("Buy-Write", FAMILY_STOCK_OPT,
        aliases=("bxm",), risk_class=RISK_LIMITED, direction=BULL,
        vol_thesis=HIGH_IV, min_legs=2, max_legs=2, has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _call(SIDE_SHORT, 0.50)),
        notes="ATM covered call at purchase; simultaneous stock+call.",
    ),
    StrategySpec("Covered Put", FAMILY_STOCK_OPT,
        aliases=("short stock covered put",), risk_class=RISK_LIMITED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=BEAR,
        min_legs=2, max_legs=2, has_stock=True,
        leg_templates=(_stock(SIDE_SHORT), _put(SIDE_SHORT, 0.30)),
        notes="Short stock + short put. Analysis-only; undefined upside risk.",
    ),
    StrategySpec("Protective Put", FAMILY_STOCK_OPT,
        aliases=("married put hedge",), risk_class=RISK_DEFINED,
        direction=BULL, vol_thesis=LOW_IV, min_legs=2, max_legs=2, has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _put(SIDE_LONG, 0.30)),
    ),
    StrategySpec("Protective Call", FAMILY_STOCK_OPT,
        aliases=("short stock hedge",), risk_class=RISK_DEFINED,
        direction=BEAR, min_legs=2, max_legs=2, has_stock=True,
        leg_templates=(_stock(SIDE_SHORT), _call(SIDE_LONG, 0.30)),
    ),
    StrategySpec("Married Put", FAMILY_STOCK_OPT,
        aliases=("synthetic long call",), risk_class=RISK_DEFINED,
        direction=BULL, vol_thesis=LOW_IV, min_legs=2, max_legs=2, has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _put(SIDE_LONG, 0.50)),
    ),
    StrategySpec("Collar", FAMILY_STOCK_OPT,
        aliases=("risk collar",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=HIGH_IV, min_legs=3, max_legs=3, has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _put(SIDE_LONG, 0.25), _call(SIDE_SHORT, 0.25)),
    ),
    StrategySpec("Zero-Cost Collar", FAMILY_STOCK_OPT,
        aliases=("costless collar",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=3, max_legs=3, has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _put(SIDE_LONG, 0.20), _call(SIDE_SHORT, 0.30)),
        notes="Strikes chosen so net premium = 0.",
    ),
    StrategySpec("Put-Spread Collar", FAMILY_STOCK_OPT,
        aliases=("collar put spread",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=4, max_legs=4, has_stock=True,
        leg_templates=(_stock(SIDE_LONG),_put(SIDE_LONG,0.35),_put(SIDE_SHORT,0.20),_call(SIDE_SHORT,0.25)),
    ),
    StrategySpec("Seagull Collar", FAMILY_STOCK_OPT,
        aliases=("seagull",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=4, max_legs=4, has_stock=True,
        leg_templates=(_stock(SIDE_LONG),_call(SIDE_SHORT,0.30),_put(SIDE_LONG,0.30),_put(SIDE_SHORT,0.15)),
    ),
    StrategySpec("Covered Strangle", FAMILY_STOCK_OPT,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=NEUTRAL, vol_thesis=HIGH_IV, min_legs=3, max_legs=3, has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _call(SIDE_SHORT, 0.25), _put(SIDE_SHORT, 0.25)),
    ),
    StrategySpec("Poor Man's Covered Call", FAMILY_STOCK_OPT,
        aliases=("pmcc", "diagonal spread bullish"),
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG, 0.70, slot="LEAPS"), _call(SIDE_SHORT, 0.30)),
    ),
    StrategySpec("Poor Man's Covered Put", FAMILY_STOCK_OPT,
        aliases=("pmcp",), risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG, 0.70, slot="LEAPS"), _put(SIDE_SHORT, 0.30)),
    ),
    StrategySpec("Synthetic Covered Call", FAMILY_STOCK_OPT,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_LONG,0.80),_put(SIDE_SHORT,0.80),_call(SIDE_SHORT,0.30)),
        notes="Synthetic stock (long call + short put) + covered call.",
    ),
    StrategySpec("Synthetic Covered Put", FAMILY_STOCK_OPT,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_SHORT,0.80),_put(SIDE_LONG,0.80),_put(SIDE_SHORT,0.30)),
    ),
    StrategySpec("Stock Repair", FAMILY_STOCK_OPT,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=3, max_legs=3, has_stock=True,
        leg_templates=(_stock(SIDE_LONG),_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30,ratio=2)),
        notes="Recover from losing stock position; ratio call spread overlay.",
    ),
    StrategySpec("Wheel Strategy", FAMILY_STOCK_OPT,
        aliases=("triple income wheel",), risk_class=RISK_LIMITED,
        direction=BULL, vol_thesis=HIGH_IV, min_legs=1, max_legs=2,
        leg_templates=(_put(SIDE_SHORT, 0.30),),
        notes="CSP → assignment → covered call cycle.",
    ),
    StrategySpec("Dynamic Collar", FAMILY_STOCK_OPT,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=3, max_legs=4, has_stock=True,
        leg_templates=(_stock(SIDE_LONG), _put(SIDE_LONG, 0.25), _call(SIDE_SHORT, 0.30)),
        notes="Actively rolled collar adjusting strikes to market moves.",
    ),

    # ── 3. CALL_SPREADS (10) ──────────────────────────────────────────────
    StrategySpec("Bull Call Debit Spread", FAMILY_CALL_SPREAD,
        aliases=("bull call spread",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30)),
    ),
    StrategySpec("Bull Call Debit Spread ITM", FAMILY_CALL_SPREAD,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.65),_call(SIDE_SHORT,0.50)),
    ),
    StrategySpec("Bull Call Debit Spread OTM", FAMILY_CALL_SPREAD,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.35),_call(SIDE_SHORT,0.20)),
    ),
    StrategySpec("Bear Call Credit Spread", FAMILY_CALL_SPREAD,
        aliases=("call credit spread",), risk_class=RISK_DEFINED, direction=BEAR,
        vol_thesis=HIGH_IV, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.35),_call(SIDE_LONG,0.20)),
    ),
    StrategySpec("Bear Call Credit Spread OTM", FAMILY_CALL_SPREAD,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.25),_call(SIDE_LONG,0.15)),
    ),
    StrategySpec("Narrow Bull Call Spread", FAMILY_CALL_SPREAD,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.40)),
        notes="Tight wing — high probability but small max profit.",
    ),
    StrategySpec("Wide Bull Call Spread", FAMILY_CALL_SPREAD,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.15)),
    ),
    StrategySpec("LEAPS Bull Call Spread", FAMILY_CALL_SPREAD,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2, min_dte=181,
        leg_templates=(_call(SIDE_LONG,0.60,slot="LEAPS"),_call(SIDE_SHORT,0.35,slot="LEAPS")),
    ),
    StrategySpec("Weekly Bear Call Spread", FAMILY_CALL_SPREAD,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2, min_dte=2, max_dte=8,
        leg_templates=(_call(SIDE_SHORT,0.30),_call(SIDE_LONG,0.15)),
    ),
    StrategySpec("Call Spread Roll-Up-Out", FAMILY_CALL_SPREAD,
        aliases=("roll up and out",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30,slot="BACK")),
        notes="Diagonal call spread — bullish + carry.",
    ),

    # ── 4. PUT_SPREADS (10) ───────────────────────────────────────────────
    StrategySpec("Bear Put Debit Spread", FAMILY_PUT_SPREAD,
        aliases=("bear put spread",), risk_class=RISK_DEFINED, direction=BEAR,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.30)),
    ),
    StrategySpec("Bear Put Debit Spread ITM", FAMILY_PUT_SPREAD,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.65),_put(SIDE_SHORT,0.50)),
    ),
    StrategySpec("Bear Put Debit Spread OTM", FAMILY_PUT_SPREAD,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.35),_put(SIDE_SHORT,0.20)),
    ),
    StrategySpec("Bull Put Credit Spread", FAMILY_PUT_SPREAD,
        aliases=("put credit spread",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=HIGH_IV, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_SHORT,0.35),_put(SIDE_LONG,0.20)),
    ),
    StrategySpec("Bull Put Credit Spread OTM", FAMILY_PUT_SPREAD,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_SHORT,0.25),_put(SIDE_LONG,0.15)),
    ),
    StrategySpec("Narrow Bear Put Spread", FAMILY_PUT_SPREAD,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.40)),
    ),
    StrategySpec("Wide Bear Put Spread", FAMILY_PUT_SPREAD,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.15)),
    ),
    StrategySpec("LEAPS Bear Put Spread", FAMILY_PUT_SPREAD,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2, min_dte=181,
        leg_templates=(_put(SIDE_LONG,0.60,slot="LEAPS"),_put(SIDE_SHORT,0.35,slot="LEAPS")),
    ),
    StrategySpec("Weekly Bull Put Spread", FAMILY_PUT_SPREAD,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2, min_dte=2, max_dte=8,
        leg_templates=(_put(SIDE_SHORT,0.30),_put(SIDE_LONG,0.15)),
    ),
    StrategySpec("Put Spread Roll-Down-Out", FAMILY_PUT_SPREAD,
        aliases=("roll down and out",), risk_class=RISK_DEFINED, direction=BEAR,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.30,slot="BACK")),
    ),

    # ── 5. SYNTHETIC_COMBINATION (8) ──────────────────────────────────────
    StrategySpec("Bullish Risk Reversal", FAMILY_SYNTHETIC,
        aliases=("risk reversal bull",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.25),_put(SIDE_SHORT,0.25)),
        notes="Sell OTM put to finance OTM call; bullish bias.",
    ),
    StrategySpec("Bearish Risk Reversal", FAMILY_SYNTHETIC,
        aliases=("risk reversal bear",), risk_class=RISK_DEFINED, direction=BEAR,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.25),_call(SIDE_SHORT,0.25)),
    ),
    StrategySpec("Synthetic Long Stock", FAMILY_SYNTHETIC,
        aliases=("synthetic long",), risk_class=RISK_UNDEFINED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=BULL,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_put(SIDE_SHORT,0.50)),
        notes="Analysis-only; unlimited downside on short put in distress.",
    ),
    StrategySpec("Synthetic Short Stock", FAMILY_SYNTHETIC,
        aliases=("synthetic short",), risk_class=RISK_UNDEFINED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=BEAR,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50),_call(SIDE_SHORT,0.50)),
    ),
    StrategySpec("Split-Strike Synthetic Bullish", FAMILY_SYNTHETIC,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.35),_put(SIDE_SHORT,0.20)),
        notes="OTM call + OTM short put; defined via net credit / OTM put risk.",
    ),
    StrategySpec("Split-Strike Synthetic Bearish", FAMILY_SYNTHETIC,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.35),_call(SIDE_SHORT,0.20)),
    ),
    StrategySpec("Double Bull Spread", FAMILY_SYNTHETIC,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30),
                       _put(SIDE_SHORT,0.35),_put(SIDE_LONG,0.20)),
        notes="Bull call spread + bull put spread same expiry.",
    ),
    StrategySpec("Double Bear Spread", FAMILY_SYNTHETIC,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.30),
                       _call(SIDE_SHORT,0.35),_call(SIDE_LONG,0.20)),
    ),

    # ── 6. CALENDAR (12) ─────────────────────────────────────────────────
    StrategySpec("Long Call Calendar", FAMILY_CALENDAR,
        aliases=("call horizontal", "atm call calendar"),
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.50,slot="FRONT"),_call(SIDE_LONG,0.50,slot="BACK")),
        notes="Profits when underlying stays near short strike; IV expansion helps back.",
    ),
    StrategySpec("Long Put Calendar", FAMILY_CALENDAR,
        aliases=("put horizontal", "atm put calendar"),
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_SHORT,0.50,slot="FRONT"),_put(SIDE_LONG,0.50,slot="BACK")),
    ),
    StrategySpec("Long Call Calendar ITM", FAMILY_CALENDAR,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.65,slot="FRONT"),_call(SIDE_LONG,0.65,slot="BACK")),
    ),
    StrategySpec("Long Call Calendar OTM", FAMILY_CALENDAR,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.30,slot="FRONT"),_call(SIDE_LONG,0.30,slot="BACK")),
    ),
    StrategySpec("Short Call Calendar", FAMILY_CALENDAR,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=ANY, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50,slot="FRONT"),_call(SIDE_SHORT,0.50,slot="BACK")),
        notes="Benefits from IV crush or fast directional move; undefined risk at back expiry.",
    ),
    StrategySpec("Double Calendar", FAMILY_CALENDAR,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_SHORT,0.30,slot="FRONT"),_call(SIDE_LONG,0.30,slot="BACK"),
                       _put(SIDE_SHORT,0.30,slot="FRONT"),_put(SIDE_LONG,0.30,slot="BACK")),
    ),
    StrategySpec("Earnings Calendar", FAMILY_CALENDAR,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2, min_dte=2, max_dte=45,
        leg_templates=(_call(SIDE_SHORT,0.50,slot="FRONT"),_call(SIDE_LONG,0.50,slot="BACK")),
        notes="Front expiry = earnings date; back benefits from post-event vol.",
    ),
    StrategySpec("LEAPS Calendar Call", FAMILY_CALENDAR,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2, min_dte=30,
        leg_templates=(_call(SIDE_SHORT,0.50,slot="MONTHLY"),_call(SIDE_LONG,0.50,slot="LEAPS")),
    ),
    StrategySpec("LEAPS Calendar Put", FAMILY_CALENDAR,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2, min_dte=30,
        leg_templates=(_put(SIDE_SHORT,0.50,slot="MONTHLY"),_put(SIDE_LONG,0.50,slot="LEAPS")),
    ),
    StrategySpec("Ratio Calendar", FAMILY_CALENDAR,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=NEUTRAL, min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_SHORT,0.50,slot="FRONT"),
                       _call(SIDE_LONG,0.50,slot="BACK"),
                       _call(SIDE_SHORT,0.50,slot="BACK")),
        notes="Extra short back-month; undefined if underlying gaps through strike.",
    ),
    StrategySpec("Calendarized Vertical", FAMILY_CALENDAR,
        aliases=("calendar spread diagonal",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),_call(SIDE_SHORT,0.30,slot="FRONT")),
    ),
    StrategySpec("Reverse Calendar", FAMILY_CALENDAR,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=ANY, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50,slot="FRONT"),_call(SIDE_SHORT,0.50,slot="BACK")),
    ),

    # ── 7. DIAGONAL (14) ─────────────────────────────────────────────────
    StrategySpec("Long Call Diagonal Bullish", FAMILY_DIAGONAL,
        aliases=("bullish diagonal", "bull diagonal"),
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.60,slot="BACK"),_call(SIDE_SHORT,0.30,slot="FRONT")),
    ),
    StrategySpec("Long Put Diagonal Bearish", FAMILY_DIAGONAL,
        aliases=("bearish diagonal", "bear diagonal"),
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.60,slot="BACK"),_put(SIDE_SHORT,0.30,slot="FRONT")),
    ),
    StrategySpec("Debit Call Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),_call(SIDE_SHORT,0.40,slot="FRONT")),
    ),
    StrategySpec("Credit Call Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.50,slot="BACK"),_call(SIDE_LONG,0.30,slot="FRONT")),
    ),
    StrategySpec("Double Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.35,slot="BACK"),_call(SIDE_SHORT,0.20,slot="FRONT"),
                       _put(SIDE_LONG,0.35,slot="BACK"),_put(SIDE_SHORT,0.20,slot="FRONT")),
    ),
    StrategySpec("LEAPS Diagonal Call", FAMILY_DIAGONAL,
        aliases=("pmcc variant",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2, min_dte=90,
        leg_templates=(_call(SIDE_LONG,0.70,slot="LEAPS"),_call(SIDE_SHORT,0.30,slot="FRONT")),
    ),
    StrategySpec("LEAPS Diagonal Put", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2, min_dte=90,
        leg_templates=(_put(SIDE_LONG,0.70,slot="LEAPS"),_put(SIDE_SHORT,0.30,slot="FRONT")),
    ),
    StrategySpec("Earnings Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),_call(SIDE_SHORT,0.40,slot="FRONT")),
        notes="Front expires on/after earnings; back leg holds residual value.",
    ),
    StrategySpec("Broken-Wing Call Diagonal", FAMILY_DIAGONAL,
        aliases=("broken wing call diag",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),_call(SIDE_SHORT,0.20,slot="FRONT")),
        notes="Wide OTM short; asymmetric risk profile.",
    ),
    StrategySpec("Broken-Wing Put Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50,slot="BACK"),_put(SIDE_SHORT,0.20,slot="FRONT")),
    ),
    StrategySpec("Diagonal Straddle", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=NEUTRAL, min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),_call(SIDE_SHORT,0.50,slot="FRONT"),
                       _put(SIDE_LONG,0.50,slot="BACK"),_put(SIDE_SHORT,0.50,slot="FRONT")),
    ),
    StrategySpec("Rolling Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.60,slot="QUARTERLY"),_call(SIDE_SHORT,0.30,slot="FRONT")),
        notes="Systematically roll front short; long-term LEAPS as anchor.",
    ),
    StrategySpec("Ratio Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=BULL, min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_LONG,0.60,slot="BACK"),
                       _call(SIDE_SHORT,0.30,slot="FRONT"),
                       _call(SIDE_SHORT,0.30,slot="FRONT")),
    ),
    StrategySpec("Short Call Diagonal", FAMILY_DIAGONAL,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=BEAR, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.60,slot="BACK"),_call(SIDE_LONG,0.30,slot="FRONT")),
    ),

    # ── 8. STRADDLE_STRANGLE (10) ─────────────────────────────────────────
    StrategySpec("Long Straddle", FAMILY_STRADDLE,
        aliases=("buy straddle",), risk_class=RISK_DEFINED, direction=NEUTRAL,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_put(SIDE_LONG,0.50)),
        notes="Profits from large moves in either direction. Best pre-event.",
    ),
    StrategySpec("Long Strangle", FAMILY_STRADDLE,
        aliases=("buy strangle",), risk_class=RISK_DEFINED, direction=NEUTRAL,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.25),_put(SIDE_LONG,0.25)),
        notes="Cheaper than straddle; needs larger move to profit.",
    ),
    StrategySpec("Short Straddle", FAMILY_STRADDLE,
        aliases=("sell straddle",), risk_class=RISK_UNDEFINED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.50),_put(SIDE_SHORT,0.50)),
    ),
    StrategySpec("Short Strangle", FAMILY_STRADDLE,
        aliases=("sell strangle",), risk_class=RISK_UNDEFINED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.25),_put(SIDE_SHORT,0.25)),
    ),
    StrategySpec("Strap", FAMILY_STRADDLE,
        risk_class=RISK_DEFINED, direction=BULL, vol_thesis=LOW_IV,
        min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_LONG,0.50,ratio=2),_put(SIDE_LONG,0.50)),
        notes="2 calls + 1 put; profits more from upside move.",
    ),
    StrategySpec("Strip", FAMILY_STRADDLE,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_LONG,0.50),_put(SIDE_LONG,0.50,ratio=2)),
        notes="1 call + 2 puts; profits more from downside move.",
    ),
    StrategySpec("Iron Straddle", FAMILY_STRADDLE,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_SHORT,0.50),_put(SIDE_SHORT,0.50),
                       _call(SIDE_LONG,0.20),_put(SIDE_LONG,0.20)),
        notes="Short ATM straddle + OTM wings for cap; aka iron fly.",
    ),
    StrategySpec("Reverse Ratio Straddle", FAMILY_STRADDLE,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.50,ratio=2),_put(SIDE_LONG,0.50,ratio=2),
                       _call(SIDE_SHORT,0.35),_put(SIDE_SHORT,0.35)),
    ),
    StrategySpec("Calendar Straddle", FAMILY_STRADDLE,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_SHORT,0.50,slot="FRONT"),_call(SIDE_LONG,0.50,slot="BACK"),
                       _put(SIDE_SHORT,0.50,slot="FRONT"),_put(SIDE_LONG,0.50,slot="BACK")),
    ),
    StrategySpec("Diagonal Strangle", FAMILY_STRADDLE,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.30,slot="BACK"),_call(SIDE_SHORT,0.20,slot="FRONT"),
                       _put(SIDE_LONG,0.30,slot="BACK"),_put(SIDE_SHORT,0.20,slot="FRONT")),
    ),

    # ── 9. BUTTERFLY (14) ─────────────────────────────────────────────────
    StrategySpec("Long Call Butterfly", FAMILY_BUTTERFLY,
        aliases=("call butterfly", "long fly"),
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=3, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.55),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.45)),
        notes="Max profit if underlying lands at short strike at expiry.",
    ),
    StrategySpec("Long Put Butterfly", FAMILY_BUTTERFLY,
        aliases=("put butterfly",), risk_class=RISK_DEFINED, direction=NEUTRAL,
        vol_thesis=LOW_IV, min_legs=3, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.55),_put(SIDE_SHORT,0.50,ratio=2),_put(SIDE_LONG,0.45)),
    ),
    StrategySpec("Iron Butterfly", FAMILY_BUTTERFLY,
        aliases=("iron fly", "ibf"),
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.25),_call(SIDE_SHORT,0.50),
                       _put(SIDE_SHORT,0.50),_put(SIDE_LONG,0.25)),
        notes="Short ATM straddle + OTM wings; high credit, narrow profitable zone.",
    ),
    StrategySpec("Broken-Wing Call Butterfly", FAMILY_BUTTERFLY,
        aliases=("bwb call",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=3, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.55),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.35)),
        notes="Asymmetric wings; eliminates downside loss in exchange for upside cap.",
    ),
    StrategySpec("Broken-Wing Put Butterfly", FAMILY_BUTTERFLY,
        aliases=("bwb put",), risk_class=RISK_DEFINED, direction=BEAR,
        min_legs=3, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.55),_put(SIDE_SHORT,0.50,ratio=2),_put(SIDE_LONG,0.35)),
    ),
    StrategySpec("Unbalanced Call Butterfly", FAMILY_BUTTERFLY,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.55,ratio=1),_call(SIDE_SHORT,0.50,ratio=3),_call(SIDE_LONG,0.40,ratio=2)),
    ),
    StrategySpec("Skip-Strike Call Butterfly", FAMILY_BUTTERFLY,
        aliases=("skip strike fly",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_LONG,0.55),_call(SIDE_SHORT,0.45,ratio=2),_call(SIDE_LONG,0.30)),
        notes="Skips one strike between body and wing.",
    ),
    StrategySpec("Wide-Wing Butterfly", FAMILY_BUTTERFLY,
        risk_class=RISK_DEFINED, direction=NEUTRAL, min_legs=3, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.65),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.35)),
    ),
    StrategySpec("Narrow-Wing Butterfly", FAMILY_BUTTERFLY,
        risk_class=RISK_DEFINED, direction=NEUTRAL, min_legs=3, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.52),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.48)),
    ),
    StrategySpec("Christmas Tree Call", FAMILY_BUTTERFLY,
        aliases=("xmas tree",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.35),
                       _call(SIDE_SHORT,0.25),_call(SIDE_SHORT,0.15)),
        notes="Long ATM + short 3 OTM calls; directional butterfly variant.",
    ),
    StrategySpec("Double Butterfly", FAMILY_BUTTERFLY,
        risk_class=RISK_DEFINED, direction=NEUTRAL, min_legs=6, max_legs=8,
        leg_templates=(_call(SIDE_LONG,0.55),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.45),
                       _put(SIDE_LONG,0.55),_put(SIDE_SHORT,0.50,ratio=2),_put(SIDE_LONG,0.45)),
    ),
    StrategySpec("Reverse Butterfly", FAMILY_BUTTERFLY,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=NEUTRAL, min_legs=3, max_legs=4,
        leg_templates=(_call(SIDE_SHORT,0.55),_call(SIDE_LONG,0.50,ratio=2),_call(SIDE_SHORT,0.45)),
        notes="Short the body, long the wings; undefined risk with no hard max loss.",
    ),
    StrategySpec("Calendar Butterfly", FAMILY_BUTTERFLY,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=3, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),
                       _call(SIDE_SHORT,0.50,ratio=2,slot="FRONT"),
                       _call(SIDE_LONG,0.50,slot="QUARTERLY")),
    ),
    StrategySpec("Earnings Butterfly", FAMILY_BUTTERFLY,
        aliases=("event fly",), risk_class=RISK_DEFINED, direction=NEUTRAL,
        min_legs=3, max_legs=4, min_dte=2, max_dte=21,
        leg_templates=(_call(SIDE_LONG,0.55),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.40)),
        notes="Short strike centered on expected post-event price.",
    ),

    # ── 10. CONDOR (12) ───────────────────────────────────────────────────
    StrategySpec("Iron Condor", FAMILY_CONDOR,
        aliases=("ic", "iron condor standard"),
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.15),_put(SIDE_SHORT,0.30),
                       _call(SIDE_SHORT,0.30),_call(SIDE_LONG,0.15)),
        notes="Collect credit outside expected move range.",
    ),
    StrategySpec("Iron Condor Narrow", FAMILY_CONDOR,
        aliases=("narrow ic",), risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.20),_put(SIDE_SHORT,0.35),
                       _call(SIDE_SHORT,0.35),_call(SIDE_LONG,0.20)),
        notes="Higher credit; higher probability of touch.",
    ),
    StrategySpec("Iron Condor Wide", FAMILY_CONDOR,
        aliases=("wide ic",), risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.08),_put(SIDE_SHORT,0.20),
                       _call(SIDE_SHORT,0.20),_call(SIDE_LONG,0.08)),
        notes="Smaller credit; wider profitable zone.",
    ),
    StrategySpec("Reverse Iron Condor", FAMILY_CONDOR,
        aliases=("ric",), risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_SHORT,0.15),_put(SIDE_LONG,0.30),
                       _call(SIDE_LONG,0.30),_call(SIDE_SHORT,0.15)),
        notes="Pay debit; profits from large moves outside wings.",
    ),
    StrategySpec("Broken-Wing Iron Condor", FAMILY_CONDOR,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.25),
                       _call(SIDE_SHORT,0.30),_call(SIDE_LONG,0.20)),
        notes="Wider put wing; asymmetric credit favors upside.",
    ),
    StrategySpec("Asymmetric Iron Condor", FAMILY_CONDOR,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.20),
                       _call(SIDE_SHORT,0.35),_call(SIDE_LONG,0.20)),
        notes="Wider call credit side vs put protection.",
    ),
    StrategySpec("Double Condor", FAMILY_CONDOR,
        risk_class=RISK_DEFINED, direction=NEUTRAL, min_legs=8, max_legs=8,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.25),
                       _call(SIDE_SHORT,0.25),_call(SIDE_LONG,0.10),
                       _put(SIDE_LONG,0.30),_put(SIDE_SHORT,0.40),
                       _call(SIDE_SHORT,0.40),_call(SIDE_LONG,0.30)),
    ),
    StrategySpec("Skewed Iron Condor", FAMILY_CONDOR,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.20),_put(SIDE_SHORT,0.35),
                       _call(SIDE_SHORT,0.25),_call(SIDE_LONG,0.10)),
        notes="Bearish skew; heavier put-side credit.",
    ),
    StrategySpec("Delta-Neutral Iron Condor", FAMILY_CONDOR,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_LONG,0.15),_put(SIDE_SHORT,0.30),
                       _call(SIDE_SHORT,0.30),_call(SIDE_LONG,0.15)),
        notes="Strikes chosen to achieve delta ≈ 0 at entry.",
    ),
    StrategySpec("Earnings Iron Condor", FAMILY_CONDOR,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4, min_dte=2, max_dte=14,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.25),
                       _call(SIDE_SHORT,0.25),_call(SIDE_LONG,0.10)),
        notes="Sell premium at event; wings sized to expected move.",
    ),
    StrategySpec("Zero-DTE Iron Condor", FAMILY_CONDOR,
        aliases=("0dte ic",), risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4, min_dte=0, max_dte=1,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.20),
                       _call(SIDE_SHORT,0.20),_call(SIDE_LONG,0.10)),
        notes="Same-day expiry; extreme theta decay; gamma risk very high.",
    ),
    StrategySpec("Zero-DTE Iron Butterfly", FAMILY_CONDOR,
        aliases=("0dte ifly",), risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4, min_dte=0, max_dte=1,
        leg_templates=(_put(SIDE_SHORT,0.50),_call(SIDE_SHORT,0.50),
                       _put(SIDE_LONG,0.15),_call(SIDE_LONG,0.15)),
    ),

    # ── 11. RATIO_BACKSPREAD (12) ─────────────────────────────────────────
    StrategySpec("Call Ratio Spread 1x2", FAMILY_RATIO,
        aliases=("call ratio 1x2",), risk_class=RISK_UNDEFINED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=BULL,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30,ratio=2)),
        notes="Undefined upside risk if extra short call goes deep ITM.",
    ),
    StrategySpec("Put Ratio Spread 1x2", FAMILY_RATIO,
        aliases=("put ratio 1x2",), risk_class=RISK_UNDEFINED,
        execution_mode=MODE_ANALYSIS_ONLY, direction=BEAR,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.30,ratio=2)),
    ),
    StrategySpec("Call Backspread 2x1", FAMILY_RATIO,
        aliases=("call backspread",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_SHORT,0.50),_call(SIDE_LONG,0.30,ratio=2)),
        notes="Buy 2 OTM calls; sell 1 ATM call. Net credit or near zero cost.",
    ),
    StrategySpec("Put Backspread 2x1", FAMILY_RATIO,
        aliases=("put backspread",), risk_class=RISK_DEFINED, direction=BEAR,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_SHORT,0.50),_put(SIDE_LONG,0.30,ratio=2)),
    ),
    StrategySpec("Call Ratio Spread 1x3", FAMILY_RATIO,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.25,ratio=3)),
    ),
    StrategySpec("Put Ratio Spread 1x3", FAMILY_RATIO,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=BEAR, min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.25,ratio=3)),
    ),
    StrategySpec("Bullish Seagull", FAMILY_RATIO,
        aliases=("seagull spread bull",), risk_class=RISK_DEFINED, direction=BULL,
        min_legs=3, max_legs=3,
        leg_templates=(_put(SIDE_SHORT,0.20),_call(SIDE_LONG,0.40),_call(SIDE_SHORT,0.20)),
        notes="Short OTM put finances debit call spread; bullish with downside exposure to put.",
    ),
    StrategySpec("Bearish Seagull", FAMILY_RATIO,
        aliases=("seagull spread bear",), risk_class=RISK_DEFINED, direction=BEAR,
        min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_SHORT,0.20),_put(SIDE_LONG,0.40),_put(SIDE_SHORT,0.20)),
    ),
    StrategySpec("Covered Ratio Spread Call", FAMILY_RATIO,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=3, max_legs=3, has_stock=True,
        leg_templates=(_stock(SIDE_LONG),_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30,ratio=2)),
        notes="Stock + long ATM call + 2 short OTM calls; covered so defined risk.",
    ),
    StrategySpec("Zero-Cost Call Ratio Spread", FAMILY_RATIO,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=BULL, min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.25,ratio=2)),
        notes="Strikes chosen so net cost = 0; analysis-only for the extra short leg.",
    ),
    StrategySpec("Broken-Wing Call Ratio", FAMILY_RATIO,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_LONG,0.55,ratio=1),_call(SIDE_SHORT,0.35,ratio=2),_call(SIDE_LONG,0.20,ratio=1)),
        notes="Defined risk via lower long wing; butterfly variant.",
    ),
    StrategySpec("Broken-Wing Put Ratio", FAMILY_RATIO,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=3, max_legs=3,
        leg_templates=(_put(SIDE_LONG,0.55,ratio=1),_put(SIDE_SHORT,0.35,ratio=2),_put(SIDE_LONG,0.20,ratio=1)),
    ),

    # ── 12. ADVANCED_INCOME_VOL (15) ──────────────────────────────────────
    StrategySpec("Jade Lizard", FAMILY_ADVANCED,
        aliases=("jade lizard spread",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=HIGH_IV, min_legs=3, max_legs=3,
        leg_templates=(_put(SIDE_SHORT,0.30),_call(SIDE_SHORT,0.25),_call(SIDE_LONG,0.15)),
        notes="Short OTM put + short OTM call spread; no upside risk if credit > call spread width.",
    ),
    StrategySpec("Reverse Jade Lizard", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=HIGH_IV,
        min_legs=3, max_legs=3,
        leg_templates=(_call(SIDE_SHORT,0.30),_put(SIDE_SHORT,0.25),_put(SIDE_LONG,0.15)),
        notes="Mirror of jade lizard; no downside risk if credit > put spread width.",
    ),
    StrategySpec("Big Lizard", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=3, max_legs=3,
        leg_templates=(_put(SIDE_SHORT,0.50),_call(SIDE_SHORT,0.25),_call(SIDE_LONG,0.10)),
        notes="ATM short put + OTM call spread; higher credit but large put risk.",
    ),
    StrategySpec("Twisted Sister", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_put(SIDE_SHORT,0.30),_put(SIDE_LONG,0.15),
                       _call(SIDE_SHORT,0.30),_call(SIDE_LONG,0.15)),
        notes="Iron condor variant with asymmetric wing sizing.",
    ),
    StrategySpec("Iron Fly", FAMILY_ADVANCED,
        aliases=("iron butterfly atm",), risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.20),_call(SIDE_SHORT,0.50),
                       _put(SIDE_SHORT,0.50),_put(SIDE_LONG,0.20)),
    ),
    StrategySpec("Reverse Iron Fly", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_SHORT,0.20),_call(SIDE_LONG,0.50),
                       _put(SIDE_LONG,0.50),_put(SIDE_SHORT,0.20)),
    ),
    StrategySpec("Tail-Risk Hedge", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.05)),
        notes="Crash put spread; OTM debit spread for tail protection.",
    ),
    StrategySpec("Crash Put Spread", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=BEAR, vol_thesis=ANY,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_LONG,0.15),_put(SIDE_SHORT,0.05)),
    ),
    StrategySpec("Buffered-Protection Structure", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=3, max_legs=4,
        leg_templates=(_stock(SIDE_LONG),_put(SIDE_LONG,0.25),_call(SIDE_SHORT,0.25),_put(SIDE_SHORT,0.10)),
        notes="Long stock + protective put funded by short call and short deep OTM put.",
    ),
    StrategySpec("Defined-Outcome Structure", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=BULL, min_legs=4, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30),
                       _put(SIDE_SHORT,0.30),_put(SIDE_LONG,0.15)),
        notes="Capped upside + capped downside; defined outcomes.",
    ),
    StrategySpec("Theta-Positive Spread", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=4,
        leg_templates=(_call(SIDE_SHORT,0.35),_put(SIDE_SHORT,0.35),
                       _call(SIDE_LONG,0.15),_put(SIDE_LONG,0.15)),
        notes="Net theta positive (defined-risk strangle with wings).",
    ),
    StrategySpec("Vega-Positive Structure", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=4,
        leg_templates=(_call(SIDE_LONG,0.50),_put(SIDE_LONG,0.50)),
        notes="Long volatility; profits from IV expansion.",
    ),
    StrategySpec("Volatility Skew Trade", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_put(SIDE_SHORT,0.25),_call(SIDE_LONG,0.25)),
        notes="Sell elevated put IV; buy cheap call IV; risk reversal.",
    ),
    StrategySpec("Term-Structure Trade", FAMILY_ADVANCED,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),_call(SIDE_SHORT,0.50,slot="FRONT")),
        notes="Buy back-month IV vs sell front-month IV; calendar spread.",
    ),
    StrategySpec("Variance Risk Premium Structure", FAMILY_ADVANCED,
        risk_class=RISK_UNDEFINED, execution_mode=MODE_ANALYSIS_ONLY,
        direction=NEUTRAL, vol_thesis=HIGH_IV, min_legs=2, max_legs=4,
        leg_templates=(_call(SIDE_SHORT,0.30),_put(SIDE_SHORT,0.30),
                       _call(SIDE_LONG,0.10),_put(SIDE_LONG,0.10)),
        notes="Analysis-only; harvests variance risk premium; needs precise delta hedging.",
    ),

    # ── 13. EVENT_EXPIRATION (12) ─────────────────────────────────────────
    StrategySpec("Earnings Long Straddle", FAMILY_EVENT,
        aliases=("event straddle",), risk_class=RISK_DEFINED, direction=NEUTRAL,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2, min_dte=2, max_dte=21,
        leg_templates=(_call(SIDE_LONG,0.50),_put(SIDE_LONG,0.50)),
        notes="Buy ATM straddle before earnings; profits from large post-event move.",
    ),
    StrategySpec("Earnings Long Strangle", FAMILY_EVENT,
        aliases=("event strangle",), risk_class=RISK_DEFINED, direction=NEUTRAL,
        vol_thesis=LOW_IV, min_legs=2, max_legs=2, min_dte=2, max_dte=21,
        leg_templates=(_call(SIDE_LONG,0.25),_put(SIDE_LONG,0.25)),
    ),
    StrategySpec("Earnings Butterfly Event", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=NEUTRAL, min_legs=3, max_legs=4, min_dte=2, max_dte=14,
        leg_templates=(_call(SIDE_LONG,0.55),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.40)),
    ),
    StrategySpec("Earnings Iron Condor Event", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4, min_dte=2, max_dte=14,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.25),
                       _call(SIDE_SHORT,0.25),_call(SIDE_LONG,0.10)),
        notes="Sell premium around expected earnings move; wings = EM width.",
    ),
    StrategySpec("Pre-Event IV-Expansion Trade", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=4, min_dte=7, max_dte=45,
        leg_templates=(_call(SIDE_LONG,0.50,slot="BACK"),_call(SIDE_SHORT,0.50,slot="FRONT")),
        notes="Calendar spread before event; back-month benefits from IV expansion.",
    ),
    StrategySpec("Post-Event IV-Crush Trade", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4, min_dte=2, max_dte=7,
        leg_templates=(_put(SIDE_LONG,0.15),_put(SIDE_SHORT,0.30),
                       _call(SIDE_SHORT,0.30),_call(SIDE_LONG,0.15)),
        notes="Sell premium immediately post-event; IV crush is the profit driver.",
    ),
    StrategySpec("Zero-DTE Vertical", FAMILY_EVENT,
        aliases=("0dte vertical",), risk_class=RISK_DEFINED, direction=BULL,
        vol_thesis=HIGH_IV, min_legs=2, max_legs=2, min_dte=0, max_dte=1,
        leg_templates=(_call(SIDE_LONG,0.50),_call(SIDE_SHORT,0.30)),
        notes="Bull call spread expiring same day; extreme time decay.",
    ),
    StrategySpec("Zero-DTE Butterfly Event", FAMILY_EVENT,
        aliases=("0dte fly",), risk_class=RISK_DEFINED, direction=NEUTRAL,
        min_legs=3, max_legs=4, min_dte=0, max_dte=1,
        leg_templates=(_call(SIDE_LONG,0.55),_call(SIDE_SHORT,0.50,ratio=2),_call(SIDE_LONG,0.45)),
    ),
    StrategySpec("Zero-DTE Iron Butterfly Event", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4, min_dte=0, max_dte=1,
        leg_templates=(_call(SIDE_LONG,0.20),_call(SIDE_SHORT,0.50),
                       _put(SIDE_SHORT,0.50),_put(SIDE_LONG,0.20)),
    ),
    StrategySpec("Zero-DTE Iron Condor Event", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=HIGH_IV,
        min_legs=4, max_legs=4, min_dte=0, max_dte=1,
        leg_templates=(_put(SIDE_LONG,0.10),_put(SIDE_SHORT,0.20),
                       _call(SIDE_SHORT,0.20),_call(SIDE_LONG,0.10)),
    ),
    StrategySpec("Weekly Strangle Event", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=NEUTRAL, vol_thesis=LOW_IV,
        min_legs=2, max_legs=2, min_dte=2, max_dte=8,
        leg_templates=(_call(SIDE_LONG,0.20),_put(SIDE_LONG,0.20)),
    ),
    StrategySpec("Overnight Gap Hedge", FAMILY_EVENT,
        risk_class=RISK_DEFINED, direction=BEAR, min_legs=2, max_legs=2,
        min_dte=0, max_dte=2,
        leg_templates=(_put(SIDE_LONG,0.30),_put(SIDE_SHORT,0.10)),
        notes="Cheap OTM put spread held overnight for gap protection.",
    ),
]

# ── Lookup indices ───────────────────────────────────────────────────────────
CATALOG_BY_NAME: dict[str, StrategySpec] = {s.name: s for s in CATALOG}

CATALOG_BY_FAMILY: dict[str, list[StrategySpec]] = {}
for _s in CATALOG:
    CATALOG_BY_FAMILY.setdefault(_s.family, []).append(_s)

AUTONOMOUS_STRATEGIES = [s for s in CATALOG if s.execution_mode == MODE_AUTONOMOUS]
ANALYSIS_ONLY_STRATEGIES = [s for s in CATALOG if s.execution_mode == MODE_ANALYSIS_ONLY]

# Build alias lookup
CATALOG_BY_ALIAS: dict[str, StrategySpec] = {}
for _s in CATALOG:
    CATALOG_BY_ALIAS[_s.name.lower()] = _s
    for _a in _s.aliases:
        CATALOG_BY_ALIAS[_a.lower()] = _s


def lookup(name: str) -> Optional[StrategySpec]:
    """Case-insensitive lookup by name or alias."""
    return CATALOG_BY_ALIAS.get(name.lower())


def families() -> list[str]:
    return sorted(CATALOG_BY_FAMILY.keys())


def count() -> dict:
    return {
        "total":          len(CATALOG),
        "autonomous":     len(AUTONOMOUS_STRATEGIES),
        "analysis_only":  len(ANALYSIS_ONLY_STRATEGIES),
        "by_family":      {f: len(s) for f, s in CATALOG_BY_FAMILY.items()},
    }
